### PR TITLE
Support DNS based Service Discovery

### PR DESCRIPTION
**Pull request by making**
This PR add new two `DiscoveryClient` implementations that depend on [native Service Discovery supported by Cloud Foundry](https://www.cloudfoundry.org/blog/polyglot-service-discovery-container-networking-cloud-foundry).

* `CloudFoundryAppServiceDiscoveryClient` uses cf-java-client and find container's index-based route (e.g. `0.billing.apps.internal`, `1.billing.apps.internal`, `2.billing.apps.internal`).
* `SimpleDnsBasedDiscoveryClient` simply uses DNS and resolve container's ip (e.g. `10.250.56.12`, `10.254.160.118`, `10.254.112.192`). does not depend on cf-java-client

By default, existing `CloudFoundryDiscoveryClient` is chosen.
Configuring `spring.cloud.cloudfoundry.discovery.use-dns=true` enables `CloudFoundryAppServiceDiscoveryClient`.
Configuring `spring.cloud.cloudfoundry.discovery.use-dns=true` **and** `spring.cloud.cloudfoundry.discovery.use-container-ip=true`enables `SimpleDnsBasedDiscoveryClient`.

This `DiscoveryClient` eliminates [the limitation of Tubrbine on Cloud Foundry](http://cloud.spring.io/spring-cloud-static/Finchley.M9/multi/multi__hystrix_timeouts_and_ribbon_clients.html#_turbine_stream) and does not need Turbine Stream.

> In some environments (such as in a PaaS setting), the classic Turbine model of pulling metrics from all the distributed Hystrix commands does not work.

#19

### CODE REVIEW

**Comment by spencergibb** [comment]
@making can you rebase?
@scottfrederick can you review?

**Comment by ryanjbaxter** [comment]
@making @scottfrederick ^^^

**Comment by making** [comment]
rebased

**Comment by spencergibb** [comment]
ping @scottfrederick

**Comment by scottfrederick** [comment]
@spencergibb @ryanjbaxter I keep coming back to this and looking at it, and I'm having a hard time deciding what we should do with it. 

Having two competing options implemented feels like overkill to me, and I think it would be better to pick just one.  

The `CloudFoundryAppServiceDiscoveryClient` approach that relies on the `apps.internal` domain seems like a better way to go with the latest abilities in CF. It's possible without any Spring Cloud support for one app to refer to another app using the `apps.internal` domain and let CF take care of routing to an individual instance; this change moves the routing decision to the client side. It's hard to say how much value this adds because AFAIK no one is asking for this kind of discovery and routing ability in Spring Cloud (even a year after this ability was proposed). 

As interesting as the technical approach is, I think we should close this PR pending real-world use cases that point to one approach over another. 

@making If you have more info to share on use cases you've seen for this, feel free to make a case for pulling this in.

**Comment by spencergibb** [comment]
I agree the new approach seems better, but for backward compatibilities sake, we need to keep the old one. We can certainly mark it deprecated. I'd like to get this merged if you agree the new one is fine @scottfrederick.

**Comment by scottfrederick** [comment]
I don't have any concerns with the implementation. It's possible with some versions of CF to override the default `app.internal` domain to a custom value, but it would be better to add that additional configuration later than to hold up this PR for that change.

**Comment by making** [comment]
> It's possible with some versions of CF to override the default app.internal domain to a custom value

Yes it's configurable since [PAS 2.3](https://docs.pivotal.io/pivotalcf/2-3/pcf-release-notes/runtime-rn.html#service-discovery).

**Comment by spencergibb** [comment]
Squashed and merged via c9ff45fc5ad6e20899dba1238b003ec388bd4e3d

**Pull request closed without merging**
